## 공통 설정
spring:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

--- ## dev 환경 설정
spring:
  config:
    activate:
      on-profile: dev

--- ## staging환경 설정
spring:
  config:
    activate:
      on-profile: staging

--- ## prod 환경 설정
spring:
  config:
    activate:
      on-profile: prod