## 공통 설정
spring:
  profiles:
    include:
      - common
      - core
      - infrastructure
  mail:
    host: smtp.gmail.com
    port: 587
    username: songhyeon4643@gmail.com
    password: WVTAHFIOJTVSURAV
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  ncp:
    sms:
      serviceId: ncp:sms:kr:311882152456:likelionuniv
      accessKey: 2PzmNYvOlzRgPuwcu4OB
      secretKey: Fc8yUdUp745SSxDDcmFaarj3as5wDg8fte00UxbX
      phoneNum: 01056971440

  ## 해당 spring fox가 스프링 2.6이상과 설정이 달라 따로 설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

## 해당 spring fox가 스프링 2.6이상과 설정이 달라 따로 설정
server:
  servlet:
    context-path: /api/admin



--- ## dev 환경 설정
spring:
  config:
    activate:
      on-profile: dev

--- ## staging환경 설정
spring:
  config:
    activate:
      on-profile: staging

--- ## prod 환경 설정
spring:
  config:
    activate:
      on-profile: prod