## 공통 설정
spring:
  profiles:
    include:
      - common
      - core
      - infrastructure
      - security
      - redis
  mail:
    host: ${protocol}
    port: 587
    username: ${Email}
    password: ${KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    ncp:
      sms:
        serviceId: ${ncp-cliud-sms-serviceId}
        accessKey: ${ncp-cliud-sms-accessKey}
        secretKey: ${ncp-cliud-sms-secretKey}
        phoneNum: ${fromPhoneNum}


  ## 해당 spring fox가 스프링 2.6이상과 설정이 달라 따로 설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

## 해당 spring fox가 스프링 2.6이상과 설정이 달라 따로 설정
server:
  servlet:
    context-path: /api/admin



--- ## dev 환경 설정
spring:
  config:
    activate:
      on-profile: dev

--- ## staging환경 설정
spring:
  config:
    activate:
      on-profile: staging

--- ## prod 환경 설정
spring:
  config:
    activate:
      on-profile: prod