## 공통 설정
kakao:
  iss: ${KAKAO_ISS}
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-url: ${KAKAO_REDIRECT_URL}
  redirect-url-for-local: ${KAKAO_REDIRECT_URL_FOR_LOCAL}
  app-key: ${KAKAO_APP_KEY}

google:
  iss: ${GOOGLE_ISS}
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-url: ${GOOGLE_REDIRECT_URL}
  redirect-url-for-local: ${GOOGLE_REDIRECT_URL_FOR_LOCAL}
  app-key: ${GOOGLE_API_KEY}
  scope: ${GOOGLE_SCOPE}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
      region: ${S3_REGION}
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
      access-domain: ${S3_ACCESS_DOMAIN}
    stack:
      auto: false
    credentials:
      instanceProfile: true

--- ## dev 환경 설정
spring:
  config:
    activate:
      on-profile: dev

--- ## staging환경 설정
spring:
  config:
    activate:
      on-profile: staging

--- ## prod 환경 설정
spring:
  config:
    activate:
      on-profile: prod

--- ## alarm(email, sms) 설정
alarm:
  email:
    sender-email: ${EMAIL_SENDER}
    sender-password: ${EMAIL_PASSWORD}
  sms:
    api-key: ${SMS_API_KEY}
    api-secret: ${SMS_API_SECRET}
    sending-number: ${SMS_SENDING_NUMBER}