spring:
  redis:
    host: 127.0.0.1
    port: 6379
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  spring:
    session:
      store-type: jdbc
  hibernate:
    ddl-auto: update
