## 공통 설정
spring:
  profiles:
    include:
      - common
      - core
      - infrastructure
      - security
      - redis
  data:
    web:
      pageable: ##페이징
        one-indexed-parameters: true #1페이지부터 시작, default:0페이지

server:
  servlet:
    context-path: /api

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    enabled: ${SWAGGER_ENABLED}
    path: '/swagger'
  swagger-ui:
    enabled: ${SWAGGER_ENABLED}
    path: '/swagger-ui.html'
    try-it-out-enabled: ${SWAGGER_TRY_IT_OUT}
    operations-sorter: alpha


--- ## dev 환경 설정
spring:
  config:
    activate:
      on-profile: dev

--- ## staging환경 설정
spring:
  config:
    activate:
      on-profile: staging

--- ## prod 환경 설정
spring:
  config:
    activate:
      on-profile: prod