server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
