## 공통 설정
spring:
  profiles:
    include:
      - common
      - core
      - infrastructure
  data:
    web:
      pageable: ##페이징
        one-indexed-parameters: true #1페이지부터 시작, default:0페이지
server:
  servlet:
    context-path: /api

--- ## dev 환경 설정
spring:
  config:
    activate:
      on-profile: dev

--- ## staging환경 설정
spring:
  config:
    activate:
      on-profile: staging

--- ## prod 환경 설정
spring:
  config:
    activate:
      on-profile: prod