server:
  port: 8081
  servelet:
    encoding:
      charset: UTF-8
      force: true
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true

#logging:
#  level:
#    '[likelion.univ]':DEBUG
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
