## 공통 설정
spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_NAME}
#    username: ${MYSQL_USERNAME}
#    password: ${MYSQL_PASSWORD}

  data:
    web:
      pageable:
        one-indexed-parameters: true
#  jpa:
#    show-sql: true
#    database: mysql
#    open-in-view: false
#    hibernate:
#      ddl-auto: none  #create update none
#    properties:
#      dialect: org.hibernate.dialect.MySQL8Dialect
#      hibernate:
#        default_batch_fetch_size: 1000
#        format_sql: true


--- ## dev 환경 설정
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

--- ## staging환경 설정
spring:
  config:
    activate:
      on-profile: staging

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
--- ## prod 환경 설정
spring:
  config:
    activate:
      on-profile: prod

--- ## test 환경 설정 for local
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/likelionuniv
    username: sa
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"


